### ISSUE TITLE
Encountering invalid DHT length when it is valid

### ISSUE THREAD

**Issue by edusporto** [kaksmet/jpeg-decoder#110]
While trying to open a valid JPG image, I got this error:
```Error: FormatError("encountered DHT with invalid length 2")```

I tracked the error back to this line:

https://github.com/kaksmet/jpeg-decoder/blob/c8e25252ec6c6888db8eb866dec47131c34949a3/src/parser.rs#L88

In version 0.1.0, this part of the program used to be like this:
```
if length <= 2 {
    return Err(Error::Format(format!("encountered {:?} with invalid length {}", marker, length)));
}
```

The ```<=``` was changed to ```<```. If it was still the way it used to be, the program would have (probably) functioned correctly.

For reference, this was the image I tried to load
![asia](https://user-images.githubusercontent.com/30930225/64081693-c285db80-ccda-11e9-9cbd-1a3fcc0affa5.jpg)

**Comment by edusporto** [comment]
My bad. The library I was using to process images was still using version 0.1.15 of jpeg-enconder. As of 0.1.16, this bug is fixed

**Comment by lovasoa** [comment]
If it's a jpeg that broke jpeg_decoder previously, then it might be worth to open a PR adding it to the tests anyway, in order to avoid any future regression.
