### ISSUE TITLE
Failed build on Windows

### ISSUE THREAD

**Issue by fryeb** [kaksmet/jpeg-decoder#26]
`cargo build` on windows results in:

`src\error.rs:63:69: 63:95 error: no associated item named 'UnexpectedEof' found for type 'std::io::error::ErrorKind' in the current scope`

`src\error.rs:63             ByteorderError::UnexpectedEOF => Error::Io(IoError::new(IoErrorKind::UnexpectedEof, err)),`

**Comment by kaksmet** [comment]
Which rust version are you using?

`UnexpectedEof` was introduced in 1.6.

**Comment by fryeb** [comment]
I was using 1.5. Hopefully updating rust will solve the issue.
