### ISSUE TITLE
Decoding fails on most images from Sony Ericsson P990i

### ISSUE THREAD

**Issue by kaj** [kaksmet/jpeg-decoder#43]
I have a bunch of pictures from an old smartphone, the Sony Ericsson P990i, which jpeg-decoder fails to decode most of (some are decoded without problem, but most fail with a `Format("did not find marker where expected")` error.

I don't  know enough about decoding jpegs to know if these images are actually broken according to the standard, but many other programs (e.g. gimp and eog) reads them just fine.  I'm afraid I also don't know enough about jpeg decoding to be any real help in finding the actual problem, but at least I've forked to https://github.com/kaj/jpeg-decoder and added a failing jpeg and a png copy of it (created with gimp) in a branch.

To reproduce:

    git clone git@github.com:kaj/jpeg-decoder.git
    cd jpeg-decoder
    git checkout failing-p990
    cargo test

(The image sonyericsson-p990i.jpg is by me and hereby released as CC0)

**Comment by kaksmet** [comment]
Thanks for reporting this and providing the image under CC0.

The issue with the image is that there are 2 extra bytes after the entropy coded data, before the EOI marker. This violates the JPEG spec, but the reference implementation, libjpeg, does allow this (newer versions prints a warning about corrupt JPEG data when decoding such files though).

I'm going to do something similar to libjpeg to allow such images to be successfully decoded. After I fix this (hopefully tomorrow) I'll publish a new version on crates.io for you to use.

**Comment by kaksmet** [comment]
0.1.6 has been published which fixes this.
