### ISSUE TITLE
Arithmetic overflow found while fuzzing

### ISSUE THREAD

**Issue by killercup** [kaksmet/jpeg-decoder#69]
I let [this fuzzer](https://github.com/rust-fuzz/targets/blob/bf31f23fc106ed31874042a26040ab6e96e43f45/image/read_jpeg.rs) run for a while (> 250k iterations), and it discovered:

> thread '\<unnamed>' panicked at 'attempt to add with overflow'
> […]
> `jpeg_decoder::huffman::derive_huffman_codes` in `src/huffman.rs:277`

You can find the full log as well as the used input here: https://gist.github.com/killercup/d836f174582ee5d90403e9920d893be2

**Comment by kaksmet** [comment]
Thanks for fuzzing and reporting, I'll take a look at it over the weekend.
